/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef first_CONSTANTS_H
#define first_CONSTANTS_H

#include "first_types.h"



class firstConstants {
 public:
  firstConstants();

};

extern const firstConstants g_first_constants;



#endif
